CREATE TABLE Breweries (
  Brewery_ID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(45) NULL,
  Location VARCHAR(45) NULL,
  PRIMARY KEY (Brewery_ID)
);

CREATE TABLE Beers (
  Beer_ID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(45) NULL,
  Style VARCHAR(45) NULL,
  ABV DECIMAL(11,2) NULL,
  Brewery_ID INT NOT NULL,
  PRIMARY KEY (Beer_ID)
);
